from model import *
def startup():
    add_to_db(Event,name='letusplay1',manager_id=1)
    add_to_db(Event,name='letusplay2',manager_id=1)
    add_to_db(Event,name='letusplay3',manager_id=1)
    add_to_db(Event,name='letusplay4',manager_id=1)
    add_to_db(Event,name='letusplay5',manager_id=1)
    add_to_db(User,username='muaz',password='1234',email='h@h.h')
    add_to_db(User,username='muazo',password='1234',email='h1@h.h')
    add_to_db(User,username='muazic',password='1234',email='h2@h.h')
    add_to_db(User,username='muazna',password='1234',email='h3@h.h')
    add_to_db(User,username='muazest',password='1234',email='he@h.h')
    add_to_db(Group, name='group1', disc='disc1', img='/static/images/group/1.jpg')
    add_to_db(Group, name='group2', disc='disc1', img='/static/images/group/2.jpg')
    add_to_db(Group, name='group3', disc='disc1', img='/static/images/group/3.jpg')
    add_to_db(Group, name='group5', disc='disc1', img='/static/images/group/4.jpg')
    add_to_db(Group, name='group6', disc='disc1', img='/static/images/group/5.jpg')
    load_data(Group,id=1)[0].group_members.append(load_data(User,id=1)[0])
    load_data(Group,id=2)[0].group_members.append(load_data(User,id=1)[0])
    load_data(Group,id=3)[0].group_members.append(load_data(User,id=1)[0])
    load_data(Group,id=4)[0].group_members.append(load_data(User,id=1)[0])
    load_data(Group,id=5)[0].group_members.append(load_data(User,id=1)[0])
    load_data(Group,id=1)[0].group_members.append(load_data(User,id=2)[0])
    load_data(Group,id=2)[0].group_members.append(load_data(User,id=2)[0])
    load_data(Group,id=3)[0].group_members.append(load_data(User,id=2)[0])
    load_data(Group,id=4)[0].group_members.append(load_data(User,id=2)[0])
    load_data(Group,id=5)[0].group_members.append(load_data(User,id=2)[0])
    load_data(Group,id=1)[0].group_members.append(load_data(User,id=3)[0])
    load_data(Group,id=2)[0].group_members.append(load_data(User,id=3)[0])
    load_data(Group,id=3)[0].group_members.append(load_data(User,id=3)[0])
    load_data(Group,id=4)[0].group_members.append(load_data(User,id=3)[0])
    load_data(Group,id=5)[0].group_members.append(load_data(User,id=3)[0])
    load_data(Group,id=1)[0].group_members.append(load_data(User,id=4)[0])
    load_data(Group,id=2)[0].group_members.append(load_data(User,id=4)[0])
    load_data(Group,id=3)[0].group_members.append(load_data(User,id=4)[0])
    load_data(Group,id=4)[0].group_members.append(load_data(User,id=4)[0])
    load_data(Group,id=5)[0].group_members.append(load_data(User,id=4)[0])
    load_data(Group,id=1)[0].group_members.append(load_data(User,id=5)[0])
    load_data(Group,id=2)[0].group_members.append(load_data(User,id=5)[0])
    load_data(Group,id=3)[0].group_members.append(load_data(User,id=5)[0])
    load_data(Group,id=4)[0].group_members.append(load_data(User,id=5)[0])
    load_data(Group,id=5)[0].group_members.append(load_data(User,id=5)[0])
    add_to_db(Post,user_id=1,ptype='text',text='**this is testal post**')
    add_to_db(Post,user_id=1,ptype='text',text='**this is testal post**')
    add_to_db(Post,user_id=1,ptype='text',text='**this is testal post**')
    add_to_db(Comment,**{'comment':'this is a comment','user_id':1,'post_id':1})
    add_to_db(Comment,**{'comment':'this is a other comment','user_id':1,'post_id':1})